service_name is expected instead of name
Otherwise you face this error
Error: Unsupported argument
│
│   on main.tf line 176, in module "database_mongo":
│  176:   name                                 = var.icd_mongo_name
│
│ An argument named "name" is not expected here.